[Settings]
ID = "5calls"

[context.production.environment]
  HUGO_VERSION = "0.62.0"
  PUBLIC_URL = "/"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.62.0"
  PUBLIC_URL = "/"

[build]
command = "yarn build && cd archives && hugo"

[[redirects]]
  from = "/issues/"
  query = {address = ":address", all = ":all"}
  to = "http://167.99.163.163:8080/issues/?all=:all&address=:address"
  status = 200

[[redirects]]
  from = "/issues/"
  query = {address = ":address"}
  to = "http://167.99.163.163:8080/issues/?address=:address"
  status = 200

[[redirects]]
  from = "/issues"
  query = {address = ":address", all = ":all"}
  to = "http://167.99.163.163:8080/issues/?all=:all&address=:address"
  status = 200

[[redirects]]
  from = "/issues"
  query = {address = ":address"}
  to = "http://167.99.163.163:8080/issues/?address=:address"
  status = 200

[[redirects]]
  from = "/issues/*"
  to = "http://167.99.163.163:8080/issues/:splat"
  status = 200

[[redirects]]
  from = "/report"
  to = "https://api.5calls.org/v1/report"
  status = 200

[[redirects]]
  from = "/photo/*"
  to = "http://167.99.163.163:8080/photo/:splat"
  status = 200

[[redirects]]
  from = "/archives/*"
  to = "/archives/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200