name: Update Archive

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.13
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - run: cd tools/archiveSync && go get . && go run main.go
