name: Update Archive

on:
  schedule:
    - cron: '4 10 * * *' # early morning pacific, for some reason midnight was not cool with our db

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v1.0.0 # setup running go
      with:
        version: 1.13
    - uses: geertvdc/setup-hub@master # setup running hub cli
    - uses: actions/checkout@v1 
    - uses: fregante/setup-git-token@v1 # auth git with github token
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: cd tools/archiveSync && go get . && go run main.go
      env:
        FIVECALLS_RDS_URL: ${{ secrets.FIVECALLS_RDS_URL }}
        FIVECALLS_RDS_READ_PASS: ${{ secrets.FIVECALLS_RDS_READ_PASS }}
    - name: Configure
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: diff content directory, always succeed so we can test the next step
      run: git diff --quiet archives/content/
    - name: PR if changes exist
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        branch_name=$(date +'%m-%d-%Y') && git checkout -b archive-${branch_name} # set new branch name to day
        git add archives/content/ # add only content from this directory
        git commit -m "updated archive content"
        hub pull-request -p -l archive -m "Archive topics update" # make a new pull request with the results
      if: failure()
