name: Update Archive

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.13
    - uses: actions/checkout@v1
    - uses: geertvdc/setup-hub@master
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: cd tools/archiveSync && go get . && go run main.go
      env:
        FIVECALLS_RDS_URL: ${{ secrets.FIVECALLS_RDS_URL }}
        FIVECALLS_RDS_READ_PASS: ${{ secrets.FIVECALLS_RDS_READ_PASS }}
    - name: Configure
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - run: git diff archives/content/
    - run: branch_name=$(date +'%m-%d-%Y') && git checkout -b archive-${branch_name}
    - run: git add archives/content/
    - run: git commit -m "updated archive content"
    - run: hub pull-request -p -l archive -m "Archive topics update"
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
